// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qanwavfrnjflperkejuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhbndhdmZybmpmbHBlcmtlanVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzU5ODgsImV4cCI6MjA2NTgxMTk4OH0.tOihUToMX7rdMCn74TB0JqSAvPB7qQr60uHtezsSffc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);